name: validate
on: [push, pull_request]
jobs:
  formatting-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        fallback-style: 'Google'

  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cpputest lcov make clang-tidy
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/bin sh -s 0.31.0
      - name: Compile
        run: make compile
      - name: Run Cpputests
        run: make ci-test
      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: "**/cpputest_*.xml"
      - name: Run clang-tidy
        run: make check
