name: validate
on: [push, pull_request]
jobs:
  formatting-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        fallback-style: 'Google'

  compile-test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: arduino/compile-sketches@v1
        with:
          cli-version: 0.31.0
          fqbn: 'arduino:avr:mega'
          libraries: |
            - name: 'Adafruit GFX Library'
              version: '1.11.1'
            - name: 'Adafruit ST7735 and ST7789 Library'
              version: '1.10.0'
          sketch-paths: |
            - snake/snake.ino

  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cpputest lcov
      - name: Run Cpputests
        run: make ci-test
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: "**/cpputest_*.xml"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          artifact: test-results
          name: JUnit Tests
          path: "**/cpputest_*.xml"
          reporter: java-junit
